version: '3.7'
services:
  nginx:
    image: nginx
    deploy:
          replicas: 4
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  service1:
    image: 127.0.01:4999/service1
    build: ./service1
    deploy:
          replicas: 4
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    environment:
      DATABASE_URI: ${DATABASE_URI}
      TEST_DB_URI: ${TEST_DB_URI}
  service2:
    image: 127.0.01:4999/service2      
    build: ./service2
    deploy:
          replicas: 4
    ports:
      - target: 5001
        published: 5001
        protocol: tcp
  service3:
    image: 127.0.01:4999/service3      
    build: ./service3
    deploy:
          replicas: 4
    ports:
      - target: 5002
        published: 5002
        protocol: tcp
  service4:
    image: 127.0.01:4999/service4
    build: ./service4
    deploy:
          replicas: 4
    ports:
      - target: 5003
        published: 5003
        protocol: tcp
  
  database: 
    image: mysql:5.7
    ports:
      - target: 3306
        published: 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: quote_archive
    volumes:
      - type: volume
        source: database-volume
        target: /var/lib/mysql

volumes:
  database-volume:        
