apiVersion: apps/v1
kind: Deployment
metadata:
  name: service4
  labels:
    app: service4
spec:
  selector:
    matchLabels:
      app: service4
  template:
    metadata:
      labels:
        app: service4
    spec:
      containers:
      - name: service4
        image: zhal73/service4
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: service4
  labels:
    app: service4
spec: 
  selector:
    app: service4
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
