apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  labels: 
    app: service1
spec:
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: zhal73/service1
        env:
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: my-secret-key
              key: DATABASE_URI 
        ports:
        - containerPort: 5000
        #command: ['sh', '-c', 'python3 create.py']
---
apiVersion: v1
kind: Service
metadata:
  name: service1
  labels:
    app: service1
spec:
  selector:
    app: service1
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
